server:
  port: 8998

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm_demo_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://localhost:3306/ssm_demo_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity

redis:
  host: localhost
  port: 6379
  max-wait: 30000 # 连接池最大阻塞等待时间（使用负值代表没有限制）
  max-active: 100 # 连接池最大连接数（使用负值代表没有限制）
  max-idle: 20    # 连接池中的最大空闲连接
  min-idle: 20    # 连接池中的最小空闲连接
  timeout: 3000   # 连接超时